//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericPublication))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AnotherClass))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/common")]
[System.Xml.Serialization.XmlRootAttribute("payload", Namespace="http://levelC/schema/3/d2Payload", IsNullable=false)]
public abstract partial class PayloadPublication {
    
    private MultilingualString feedDescriptionField;
    
    private string feedTypeField;
    
    private System.DateTime publicationTimeField;
    
    private InternationalIdentifier publicationCreatorField;
    
    private _ExtensionType _payloadPublicationExtensionField;
    
    private string langField;
    
    private string modelBaseVersionField;
    
    private string extensionNameField;
    
    private string extensionVersionField;
    
    private string profileNameField;
    
    private string profileVersionField;
    
    public PayloadPublication() {
        this.modelBaseVersionField = "3";
    }
    
    /// <remarks/>
    public MultilingualString feedDescription {
        get {
            return this.feedDescriptionField;
        }
        set {
            this.feedDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string feedType {
        get {
            return this.feedTypeField;
        }
        set {
            this.feedTypeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime publicationTime {
        get {
            return this.publicationTimeField;
        }
        set {
            this.publicationTimeField = value;
        }
    }
    
    /// <remarks/>
    public InternationalIdentifier publicationCreator {
        get {
            return this.publicationCreatorField;
        }
        set {
            this.publicationCreatorField = value;
        }
    }
    
    /// <remarks/>
    public _ExtensionType _payloadPublicationExtension {
        get {
            return this._payloadPublicationExtensionField;
        }
        set {
            this._payloadPublicationExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modelBaseVersion {
        get {
            return this.modelBaseVersionField;
        }
        set {
            this.modelBaseVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extensionName {
        get {
            return this.extensionNameField;
        }
        set {
            this.extensionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extensionVersion {
        get {
            return this.extensionVersionField;
        }
        set {
            this.extensionVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string profileName {
        get {
            return this.profileNameField;
        }
        set {
            this.profileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string profileVersion {
        get {
            return this.profileVersionField;
        }
        set {
            this.profileVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/common")]
public partial class MultilingualString {
    
    private MultilingualStringValue[] valuesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
    public MultilingualStringValue[] values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/common")]
public partial class MultilingualStringValue {
    
    private string langField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/extension")]
public partial class GenericPublicationExtended {
    
    private string greetingField;
    
    /// <remarks/>
    public string greeting {
        get {
            return this.greetingField;
        }
        set {
            this.greetingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/common")]
public partial class _GenericPublicationExtensionType {
    
    private GenericPublicationExtended genericPublicationExtendedField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    public GenericPublicationExtended genericPublicationExtended {
        get {
            return this.genericPublicationExtendedField;
        }
        set {
            this.genericPublicationExtendedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/common")]
public partial class _ExtensionType {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/common")]
public partial class InternationalIdentifier {
    
    private string countryField;
    
    private string nationalIdentifierField;
    
    private _ExtensionType _internationalIdentifierExtensionField;
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string nationalIdentifier {
        get {
            return this.nationalIdentifierField;
        }
        set {
            this.nationalIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public _ExtensionType _internationalIdentifierExtension {
        get {
            return this._internationalIdentifierExtensionField;
        }
        set {
            this._internationalIdentifierExtensionField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AnotherClass))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/common")]
public partial class GenericPublication : PayloadPublication {
    
    private string genericPublicationNameField;
    
    private _GenericPublicationExtensionType _genericPublicationExtensionField;
    
    /// <remarks/>
    public string genericPublicationName {
        get {
            return this.genericPublicationNameField;
        }
        set {
            this.genericPublicationNameField = value;
        }
    }
    
    /// <remarks/>
    public _GenericPublicationExtensionType _genericPublicationExtension {
        get {
            return this._genericPublicationExtensionField;
        }
        set {
            this._genericPublicationExtensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://levelC/schema/3/extension")]
public partial class AnotherClass : GenericPublication {
    
    private string anotherStringField;
    
    private _ExtensionType _anotherClassExtensionField;
    
    /// <remarks/>
    public string anotherString {
        get {
            return this.anotherStringField;
        }
        set {
            this.anotherStringField = value;
        }
    }
    
    /// <remarks/>
    public _ExtensionType _anotherClassExtension {
        get {
            return this._anotherClassExtensionField;
        }
        set {
            this._anotherClassExtensionField = value;
        }
    }
}
